/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/claude/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dashboard */
        get: operations["get_dashboard_api_claude_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bigquery-cost/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dashboard */
        get: operations["get_dashboard_api_bigquery_cost_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bigquery-cost/user-queries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get User Queries */
        get: operations["get_user_queries_api_bigquery_cost_user_queries_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bigquery-cost/limit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Limit Status
         * @description Estado do limite diário: gasto de hoje vs. limite + projeção de fim de dia.
         */
        get: operations["get_limit_status_api_bigquery_cost_limit_get"];
        /**
         * Put Limit
         * @description Define/atualiza o limite diário e aplica o bloqueio na quota do GCP.
         */
        put: operations["put_limit_api_bigquery_cost_limit_put"];
        post?: never;
        /**
         * Delete Limit
         * @description Remove o limite e o bloqueio da quota (volta ao teto padrão).
         */
        delete: operations["delete_limit_api_bigquery_cost_limit_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gcp-billing/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dashboard */
        get: operations["get_dashboard_api_gcp_billing_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gcp-billing/day-detail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Day Detail */
        get: operations["get_day_detail_api_gcp_billing_day_detail_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gcp-billing/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Comparison */
        get: operations["get_comparison_api_gcp_billing_compare_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/gcp-billing/day-detail/skus": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Day Service Skus */
        get: operations["get_day_service_skus_api_gcp_billing_day_detail_skus_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/invoice-cost/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dashboard */
        get: operations["get_dashboard_api_invoice_cost_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/vercel-cost/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Dashboard */
        get: operations["get_dashboard_api_vercel_cost_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Root */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthcheck */
        get: operations["healthcheck_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/budget-target": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Budget Target
         * @description Alvos por plataforma são calculados no /api/dashboard a partir do gasto SA+DV360+Xandr.
         */
        get: operations["budget_target_api_budget_target_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard Data */
        get: operations["dashboard_data_api_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dashboard Refresh */
        post: operations["dashboard_refresh_api_dashboard_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/refresh/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard Refresh Status */
        get: operations["dashboard_refresh_status_api_dashboard_refresh_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dashboard/refresh/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard Refresh Metrics */
        get: operations["dashboard_refresh_metrics_api_dashboard_refresh_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/attention/no-token-lines/observation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Save No Token Line Observation */
        post: operations["save_no_token_line_observation_api_attention_no_token_lines_observation_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/attention/no-token-lines/line-name": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Save No Token Line Name */
        post: operations["save_no_token_line_name_api_attention_no_token_lines_line_name_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/campaign/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Campaign Data */
        get: operations["campaign_data_api_campaign__token__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BqCostDashboardResponse */
        BqCostDashboardResponse: {
            /**
             * From Date
             * Format: date
             */
            from_date: string;
            /**
             * To Date
             * Format: date
             */
            to_date: string;
            /** Regions */
            regions: string[];
            /** Exchange Rate */
            exchange_rate: string;
            /** Price Usd Per Tib */
            price_usd_per_tib: string;
            /** Total Jobs */
            total_jobs: number;
            /** Total Bytes Billed */
            total_bytes_billed: number;
            /** Total Slot Ms */
            total_slot_ms: number;
            /** Total Cost Usd */
            total_cost_usd: string;
            /** Total Cost Brl */
            total_cost_brl: string;
            /** By User */
            by_user: components["schemas"]["BqCostUserRow"][];
            /** By Statement Type */
            by_statement_type: components["schemas"]["BqCostStatementRow"][];
            /** By Table */
            by_table: components["schemas"]["BqCostTableRow"][];
            /** Top Queries */
            top_queries: components["schemas"]["BqCostQueryRow"][];
            /**
             * By User Daily
             * @default []
             */
            by_user_daily: components["schemas"]["BqCostUserDailyPoint"][];
            /**
             * Cached
             * @default false
             */
            cached: boolean;
            /** Fetched At */
            fetched_at: string;
            /**
             * Currency
             * @default USD
             */
            currency: string;
            /**
             * Calibrated
             * @default false
             */
            calibrated: boolean;
            /**
             * Analysis Cost Usd
             * @default 0
             */
            analysis_cost_usd: string;
            /**
             * Analysis Cost Brl
             * @default 0
             */
            analysis_cost_brl: string;
            /**
             * Storage Cost Usd
             * @default 0
             */
            storage_cost_usd: string;
            /**
             * Storage Cost Brl
             * @default 0
             */
            storage_cost_brl: string;
            /**
             * Other Cost Usd
             * @default 0
             */
            other_cost_usd: string;
            /**
             * Other Cost Brl
             * @default 0
             */
            other_cost_brl: string;
            /**
             * Price By Region
             * @default {}
             */
            price_by_region: {
                [key: string]: string;
            };
            /**
             * Filtered Users
             * @default []
             */
            filtered_users: string[];
        };
        /**
         * BqCostLimitStatus
         * @description Estado do limite diário de gasto com BigQuery (escopo projeto).
         *
         *     `status` resume o dia: `unset` (sem limite), `ok`, `warning` (>= warn_pct),
         *     `exceeded` (gasto real já passou do limite) e `projected` (gasto atual ok,
         *     mas a projeção linear do dia estoura).
         *
         *     `enforcement` reflete o bloqueio real via quota do GCP (consumer override em
         *     `bigquery.googleapis.com/quota/query/usage`): `enforced` (override ativo),
         *     `off` (limite salvo mas sem bloqueio aplicado), `stray` (há override sem
         *     limite salvo), `error` (falha ao consultar/aplicar). Ao estourar, TODA query
         *     on-demand do projeto falha até a meia-noite do Pacífico.
         */
        BqCostLimitStatus: {
            /**
             * Day
             * Format: date
             */
            day: string;
            /** Timezone */
            timezone: string;
            /** Regions */
            regions: string[];
            /** Limit Brl */
            limit_brl: string | null;
            /** Warn Pct */
            warn_pct: string;
            /** Spent Brl */
            spent_brl: string;
            /** Spent Bytes */
            spent_bytes: number;
            /** Spent Usd */
            spent_usd: string;
            /** Projected Brl */
            projected_brl: string;
            /** Pct Used */
            pct_used: string | null;
            /** Day Fraction Elapsed */
            day_fraction_elapsed: string;
            /** Status */
            status: string;
            /** Enforcement */
            enforcement: string;
            /** Enforced Limit Mib */
            enforced_limit_mib?: number | null;
            /** Enforced Limit Tib */
            enforced_limit_tib?: string | null;
            /** Quota Effective Tib */
            quota_effective_tib?: string | null;
            /** Enforce Error */
            enforce_error?: string | null;
            /** Exchange Rate */
            exchange_rate: string;
            /** Price Usd Per Tib */
            price_usd_per_tib: string;
            /** Updated At */
            updated_at: string | null;
            /** Updated By */
            updated_by: string | null;
            /** Fetched At */
            fetched_at: string;
        };
        /** BqCostQueryRow */
        BqCostQueryRow: {
            /** Job Id */
            job_id: string;
            /** User Email */
            user_email: string | null;
            /** Statement Type */
            statement_type: string | null;
            /** Creation Time */
            creation_time: string;
            /** Bytes Billed */
            bytes_billed: number;
            /** Slot Ms */
            slot_ms: number;
            /** Cost Usd */
            cost_usd: string;
            /** Cost Brl */
            cost_brl: string;
            /** Query Preview */
            query_preview: string;
            /** Region */
            region: string;
        };
        /** BqCostStatementRow */
        BqCostStatementRow: {
            /** Statement Type */
            statement_type: string;
            /** Jobs */
            jobs: number;
            /** Bytes Billed */
            bytes_billed: number;
            /** Slot Ms */
            slot_ms: number;
            /** Cost Usd */
            cost_usd: string;
            /** Cost Brl */
            cost_brl: string;
        };
        /** BqCostTableRow */
        BqCostTableRow: {
            /** Table Fqn */
            table_fqn: string;
            /** Jobs */
            jobs: number;
            /** Bytes Billed */
            bytes_billed: number;
            /** Cost Usd */
            cost_usd: string;
            /** Cost Brl */
            cost_brl: string;
        };
        /**
         * BqCostUserDailyPoint
         * @description Custo de análise (query) de um usuário num dia — série temporal empilhada.
         */
        BqCostUserDailyPoint: {
            /**
             * Day
             * Format: date
             */
            day: string;
            /** User Email */
            user_email: string;
            /** Cost Usd */
            cost_usd: string;
            /** Cost Brl */
            cost_brl: string;
        };
        /** BqCostUserRow */
        BqCostUserRow: {
            /** User Email */
            user_email: string;
            /** Jobs */
            jobs: number;
            /** Bytes Billed */
            bytes_billed: number;
            /** Slot Ms */
            slot_ms: number;
            /** Cost Usd */
            cost_usd: string;
            /** Cost Brl */
            cost_brl: string;
        };
        /** BqLimitPayload */
        BqLimitPayload: {
            /**
             * Limit Brl
             * @description Limite diário de gasto em BRL.
             */
            limit_brl: number;
            /**
             * Warn Pct
             * @description Percentual para alerta amarelo (padrão 80).
             */
            warn_pct?: number | null;
        };
        /**
         * BqUserQueriesResponse
         * @description Padrões de query mais caros de um usuário (drill-down da tabela por usuário).
         */
        BqUserQueriesResponse: {
            /** User Email */
            user_email: string;
            /**
             * From Date
             * Format: date
             */
            from_date: string;
            /**
             * To Date
             * Format: date
             */
            to_date: string;
            /** Currency */
            currency: string;
            /** Exchange Rate */
            exchange_rate: string;
            /** Total Cost Usd */
            total_cost_usd: string;
            /** Total Cost Brl */
            total_cost_brl: string;
            /** Groups */
            groups: components["schemas"]["BqUserQueryGroup"][];
            /**
             * Cached
             * @default false
             */
            cached: boolean;
            /** Fetched At */
            fetched_at: string;
        };
        /**
         * BqUserQueryGroup
         * @description Padrão de query de um usuário (literais normalizados), agregado.
         */
        BqUserQueryGroup: {
            /** Pattern Preview */
            pattern_preview: string;
            /** Sample Query */
            sample_query: string;
            /** Statement Type */
            statement_type: string | null;
            /** Jobs */
            jobs: number;
            /** Bytes Billed */
            bytes_billed: number;
            /** Slot Ms */
            slot_ms: number;
            /** Cost Usd */
            cost_usd: string;
            /** Cost Brl */
            cost_brl: string;
        };
        /** ClaudeDashboardResponse */
        ClaudeDashboardResponse: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Exchange Rate */
            exchange_rate: string;
            /** Total Cost Usd */
            total_cost_usd: string;
            /** Total Cost Brl */
            total_cost_brl: string;
            /** Total Tokens */
            total_tokens: number;
            /** Users */
            users: components["schemas"]["ClaudeUserRow"][];
            /**
             * Cached
             * @default false
             */
            cached: boolean;
            /** Fetched At */
            fetched_at: string;
        };
        /** ClaudeUserRow */
        ClaudeUserRow: {
            /** User Name */
            user_name: string | null;
            /** User Email */
            user_email: string;
            /** Cost Usd */
            cost_usd: string;
            /** Cost Brl */
            cost_brl: string;
            /** Tokens */
            tokens: number;
        };
        /**
         * GcpBillingComparisonResponse
         * @description Comparação do período atual com o período imediatamente anterior de mesma duração.
         */
        GcpBillingComparisonResponse: {
            /**
             * From Date
             * Format: date
             */
            from_date: string;
            /**
             * To Date
             * Format: date
             */
            to_date: string;
            /**
             * Prev From Date
             * Format: date
             */
            prev_from_date: string;
            /**
             * Prev To Date
             * Format: date
             */
            prev_to_date: string;
            /** Currency */
            currency: string;
            /** Exchange Rate */
            exchange_rate: string;
            /** Current Total Usd */
            current_total_usd: string;
            /** Current Total Brl */
            current_total_brl: string;
            /** Previous Total Usd */
            previous_total_usd: string;
            /** Previous Total Brl */
            previous_total_brl: string;
            /** Delta Total Usd */
            delta_total_usd: string;
            /** Delta Total Brl */
            delta_total_brl: string;
            /** Delta Total Pct */
            delta_total_pct: string | null;
            /** By Service Delta */
            by_service_delta: components["schemas"]["GcpServiceDeltaRow"][];
            /**
             * Cached
             * @default false
             */
            cached: boolean;
            /** Fetched At */
            fetched_at: string;
        };
        /** GcpBillingDailyPoint */
        GcpBillingDailyPoint: {
            /**
             * Day
             * Format: date
             */
            day: string;
            /** Cost Usd */
            cost_usd: string;
            /** Cost Brl */
            cost_brl: string;
        };
        /** GcpBillingDashboardResponse */
        GcpBillingDashboardResponse: {
            /**
             * From Date
             * Format: date
             */
            from_date: string;
            /**
             * To Date
             * Format: date
             */
            to_date: string;
            /** Currency */
            currency: string;
            /** Exchange Rate */
            exchange_rate: string;
            /** Total Cost Usd */
            total_cost_usd: string;
            /** Total Cost Brl */
            total_cost_brl: string;
            /** Total Credits Usd */
            total_credits_usd: string;
            /** Total Gross Usd */
            total_gross_usd: string;
            /** By Project */
            by_project: components["schemas"]["GcpBillingProjectRow"][];
            /** By Service */
            by_service: components["schemas"]["GcpBillingServiceRow"][];
            /** By Sku */
            by_sku: components["schemas"]["GcpBillingSkuRow"][];
            /** Daily */
            daily: components["schemas"]["GcpBillingDailyPoint"][];
            /** Cloud Run By Label */
            cloud_run_by_label: components["schemas"]["GcpCloudRunByLabelRow"][];
            /**
             * Cached
             * @default false
             */
            cached: boolean;
            /** Fetched At */
            fetched_at: string;
        };
        /**
         * GcpBillingDayDetailResponse
         * @description Detalhamento de custo de um único dia (drill-down do gráfico diário).
         */
        GcpBillingDayDetailResponse: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Currency */
            currency: string;
            /** Exchange Rate */
            exchange_rate: string;
            /** Total Cost Usd */
            total_cost_usd: string;
            /** Total Cost Brl */
            total_cost_brl: string;
            /** Total Credits Usd */
            total_credits_usd: string;
            /** Total Gross Usd */
            total_gross_usd: string;
            /** By Project */
            by_project: components["schemas"]["GcpBillingProjectRow"][];
            /** By Service */
            by_service: components["schemas"]["GcpBillingServiceRow"][];
            /** By Sku */
            by_sku: components["schemas"]["GcpBillingSkuRow"][];
            /**
             * Cached
             * @default false
             */
            cached: boolean;
            /** Fetched At */
            fetched_at: string;
        };
        /**
         * GcpBillingDaySkusResponse
         * @description SKUs de um serviço num único dia (drill-down encadeado do detalhamento).
         */
        GcpBillingDaySkusResponse: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Service Id */
            service_id: string;
            /** Service Description */
            service_description: string | null;
            /** Currency */
            currency: string;
            /** Exchange Rate */
            exchange_rate: string;
            /** By Sku */
            by_sku: components["schemas"]["GcpBillingSkuRow"][];
            /**
             * Cached
             * @default false
             */
            cached: boolean;
            /** Fetched At */
            fetched_at: string;
        };
        /** GcpBillingProjectRow */
        GcpBillingProjectRow: {
            /** Project Id */
            project_id: string;
            /** Project Name */
            project_name: string | null;
            /** Cost Usd */
            cost_usd: string;
            /** Cost Brl */
            cost_brl: string;
            /** Credits Usd */
            credits_usd: string;
        };
        /** GcpBillingServiceRow */
        GcpBillingServiceRow: {
            /** Service Id */
            service_id: string;
            /** Service Description */
            service_description: string;
            /** Cost Usd */
            cost_usd: string;
            /** Cost Brl */
            cost_brl: string;
        };
        /** GcpBillingSkuRow */
        GcpBillingSkuRow: {
            /** Sku Id */
            sku_id: string;
            /** Sku Description */
            sku_description: string;
            /** Service Description */
            service_description: string;
            /** Cost Usd */
            cost_usd: string;
            /** Cost Brl */
            cost_brl: string;
            /** Usage Amount */
            usage_amount: string;
            /** Usage Unit */
            usage_unit: string | null;
        };
        /** GcpCloudRunByLabelRow */
        GcpCloudRunByLabelRow: {
            /** Service Name */
            service_name: string;
            /** Cost Usd */
            cost_usd: string;
            /** Cost Brl */
            cost_brl: string;
            /**
             * Requests
             * @default 0
             */
            requests: number;
            /** Cost Per Million Usd */
            cost_per_million_usd?: string | null;
            /** Cost Per Million Brl */
            cost_per_million_brl?: string | null;
            /** Latency P50 Ms */
            latency_p50_ms?: string | null;
            /** Latency P95 Ms */
            latency_p95_ms?: string | null;
            /** Latency P99 Ms */
            latency_p99_ms?: string | null;
            /** Error Rate */
            error_rate?: string | null;
        };
        /**
         * GcpServiceDeltaRow
         * @description Variação de custo de um serviço entre o período atual e o anterior.
         */
        GcpServiceDeltaRow: {
            /** Service Id */
            service_id: string;
            /** Service Description */
            service_description: string;
            /** Current Usd */
            current_usd: string;
            /** Current Brl */
            current_brl: string;
            /** Previous Usd */
            previous_usd: string;
            /** Previous Brl */
            previous_brl: string;
            /** Delta Usd */
            delta_usd: string;
            /** Delta Brl */
            delta_brl: string;
            /** Delta Pct */
            delta_pct: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InvoiceCostResponse */
        InvoiceCostResponse: {
            /**
             * From Date
             * Format: date
             */
            from_date: string;
            /**
             * To Date
             * Format: date
             */
            to_date: string;
            /** Total Invoices */
            total_invoices: number;
            /** Total Captcha Brl */
            total_captcha_brl: string;
            /** Total Invoice Reader Brl */
            total_invoice_reader_brl: string;
            /** Total Cost Brl */
            total_cost_brl: string;
            /** Avg Cost Per Invoice Brl */
            avg_cost_per_invoice_brl: string;
            /** Daily */
            daily: components["schemas"]["InvoiceDailyRow"][];
            /**
             * Cached
             * @default false
             */
            cached: boolean;
            /** Fetched At */
            fetched_at: string;
        };
        /** InvoiceDailyRow */
        InvoiceDailyRow: {
            /**
             * Day
             * Format: date
             */
            day: string;
            /** Invoices */
            invoices: number;
            /** Captcha Brl */
            captcha_brl: string;
            /** Invoice Reader Brl */
            invoice_reader_brl: string;
            /** Total Brl */
            total_brl: string;
            /** Cost Per Invoice Brl */
            cost_per_invoice_brl: string;
            /**
             * Source
             * @default estimated
             */
            source: string;
        };
        /** NoTokenLineNameBody */
        NoTokenLineNameBody: {
            /** Platform */
            platform: string;
            /**
             * Line
             * @default
             */
            line: string;
            /** Line Item Id */
            line_item_id?: string | null;
            /** Line Name */
            line_name: string;
            /** Updated By */
            updated_by?: string | null;
        };
        /** NoTokenLineObservationBody */
        NoTokenLineObservationBody: {
            /** Platform */
            platform: string;
            /** Line */
            line: string;
            /** Line Item Id */
            line_item_id?: string | null;
            /**
             * Observation
             * @default
             */
            observation: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * VercelCategoryDailyPoint
         * @description Ponto (dia, categoria de serviço) para o gráfico empilhado.
         */
        VercelCategoryDailyPoint: {
            /**
             * Day
             * Format: date
             */
            day: string;
            /** Category */
            category: string;
            /** Billed Usd */
            billed_usd: string;
            /** Billed Brl */
            billed_brl: string;
        };
        /** VercelChargeCategoryRow */
        VercelChargeCategoryRow: {
            /** Category */
            category: string;
            /** Billed Usd */
            billed_usd: string;
            /** Billed Brl */
            billed_brl: string;
            /** Share Pct */
            share_pct: string;
        };
        /** VercelCostResponse */
        VercelCostResponse: {
            /**
             * From Date
             * Format: date
             */
            from_date: string;
            /**
             * To Date
             * Format: date
             */
            to_date: string;
            /**
             * Currency
             * @default USD
             */
            currency: string;
            /** Exchange Rate */
            exchange_rate: string;
            /** Total Billed Usd */
            total_billed_usd: string;
            /** Total Billed Brl */
            total_billed_brl: string;
            /** Total Effective Usd */
            total_effective_usd: string;
            /** Total Effective Brl */
            total_effective_brl: string;
            /** Total Cost Usd */
            total_cost_usd: string;
            /** Total Cost Brl */
            total_cost_brl: string;
            /** Usage Billed Brl */
            usage_billed_brl: string;
            /** Credits Billed Brl */
            credits_billed_brl: string;
            /** Tax Billed Brl */
            tax_billed_brl: string;
            /** Projects Count */
            projects_count: number;
            /** Services Count */
            services_count: number;
            /** By Service */
            by_service: components["schemas"]["VercelServiceRow"][];
            /** By Project */
            by_project: components["schemas"]["VercelProjectRow"][];
            /** By Region */
            by_region: components["schemas"]["VercelRegionRow"][];
            /** By Charge Category */
            by_charge_category: components["schemas"]["VercelChargeCategoryRow"][];
            /** Daily */
            daily: components["schemas"]["VercelDailyRow"][];
            /** Daily By Category */
            daily_by_category: components["schemas"]["VercelCategoryDailyPoint"][];
            /** Service Categories */
            service_categories: string[];
            /**
             * Cached
             * @default false
             */
            cached: boolean;
            /** Fetched At */
            fetched_at: string;
        };
        /** VercelDailyRow */
        VercelDailyRow: {
            /**
             * Day
             * Format: date
             */
            day: string;
            /** Billed Usd */
            billed_usd: string;
            /** Billed Brl */
            billed_brl: string;
            /** Effective Usd */
            effective_usd: string;
            /** Effective Brl */
            effective_brl: string;
        };
        /** VercelProjectRow */
        VercelProjectRow: {
            /** Project Id */
            project_id: string | null;
            /** Project Name */
            project_name: string;
            /** Billed Usd */
            billed_usd: string;
            /** Billed Brl */
            billed_brl: string;
            /** Effective Usd */
            effective_usd: string;
            /** Effective Brl */
            effective_brl: string;
            /** Share Pct */
            share_pct: string;
        };
        /** VercelRegionRow */
        VercelRegionRow: {
            /** Region */
            region: string;
            /** Billed Usd */
            billed_usd: string;
            /** Billed Brl */
            billed_brl: string;
            /** Share Pct */
            share_pct: string;
        };
        /** VercelServiceRow */
        VercelServiceRow: {
            /** Service Name */
            service_name: string;
            /** Service Category */
            service_category: string;
            /** Billed Usd */
            billed_usd: string;
            /** Billed Brl */
            billed_brl: string;
            /** Effective Usd */
            effective_usd: string;
            /** Effective Brl */
            effective_brl: string;
            /** Consumed Quantity */
            consumed_quantity: number | null;
            /** Consumed Unit */
            consumed_unit: string | null;
            /** Share Pct */
            share_pct: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_dashboard_api_claude_dashboard_get: {
        parameters: {
            query?: {
                /** @description Dia no formato YYYY-MM-DD (default: hoje UTC). */
                date?: string | null;
                no_cache?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClaudeDashboardResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dashboard_api_bigquery_cost_dashboard_get: {
        parameters: {
            query?: {
                /** @description Início do intervalo (YYYY-MM-DD). */
                from?: string | null;
                /** @description Fim do intervalo (YYYY-MM-DD). */
                to?: string | null;
                /** @description Regiões BigQuery separadas por vírgula (ex: us,southamerica-east1). */
                regions?: string | null;
                /** @description Filtra por usuários (emails/SAs separados por vírgula; aceita '(sem usuário)'). */
                users?: string | null;
                no_cache?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BqCostDashboardResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_queries_api_bigquery_cost_user_queries_get: {
        parameters: {
            query: {
                /** @description Usuário (email/SA) a detalhar. */
                user_email: string;
                from?: string | null;
                to?: string | null;
                regions?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BqUserQueriesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_limit_status_api_bigquery_cost_limit_get: {
        parameters: {
            query?: {
                no_cache?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BqCostLimitStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_limit_api_bigquery_cost_limit_put: {
        parameters: {
            query?: never;
            header?: {
                "X-User-Email"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BqLimitPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BqCostLimitStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_limit_api_bigquery_cost_limit_delete: {
        parameters: {
            query?: never;
            header?: {
                "X-User-Email"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BqCostLimitStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dashboard_api_gcp_billing_dashboard_get: {
        parameters: {
            query?: {
                /** @description Início do intervalo (YYYY-MM-DD). */
                from?: string | null;
                /** @description Fim do intervalo (YYYY-MM-DD). */
                to?: string | null;
                no_cache?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GcpBillingDashboardResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_day_detail_api_gcp_billing_day_detail_get: {
        parameters: {
            query?: {
                /** @description Dia a detalhar (YYYY-MM-DD). */
                date?: string | null;
                no_cache?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GcpBillingDayDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_comparison_api_gcp_billing_compare_get: {
        parameters: {
            query?: {
                /** @description Início do intervalo atual (YYYY-MM-DD). */
                from?: string | null;
                /** @description Fim do intervalo atual (YYYY-MM-DD). */
                to?: string | null;
                no_cache?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GcpBillingComparisonResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_day_service_skus_api_gcp_billing_day_detail_skus_get: {
        parameters: {
            query?: {
                /** @description Dia (YYYY-MM-DD). */
                date?: string | null;
                /** @description ID do serviço GCP a detalhar. */
                service_id?: string | null;
                no_cache?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GcpBillingDaySkusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dashboard_api_invoice_cost_dashboard_get: {
        parameters: {
            query?: {
                /** @description Início (YYYY-MM-DD). */
                from?: string | null;
                /** @description Fim (YYYY-MM-DD). */
                to?: string | null;
                no_cache?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoiceCostResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_dashboard_api_vercel_cost_dashboard_get: {
        parameters: {
            query?: {
                /** @description Início do intervalo (YYYY-MM-DD). */
                from?: string | null;
                /** @description Fim do intervalo (YYYY-MM-DD). */
                to?: string | null;
                no_cache?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VercelCostResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    healthcheck_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    budget_target_api_budget_target_get: {
        parameters: {
            query: {
                /** @description Formato YYYY-MM */
                month: string;
                platform?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dashboard_data_api_dashboard_get: {
        parameters: {
            query?: {
                start?: string | null;
                end?: string | null;
                force_refresh?: boolean;
                clients?: string | null;
                cs?: string | null;
                campaigns?: string | null;
                campaign_status?: string | null;
                features?: string | null;
                tipo?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dashboard_refresh_api_dashboard_refresh_post: {
        parameters: {
            query?: {
                start?: string | null;
                end?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dashboard_refresh_status_api_dashboard_refresh_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    dashboard_refresh_metrics_api_dashboard_refresh_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    save_no_token_line_observation_api_attention_no_token_lines_observation_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NoTokenLineObservationBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_no_token_line_name_api_attention_no_token_lines_line_name_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NoTokenLineNameBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    campaign_data_api_campaign__token__get: {
        parameters: {
            query?: {
                start?: string | null;
                end?: string | null;
            };
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
